### ISSUE TITLE
shorter command?

### ISSUE THREAD

**Issue by zhangsw1412** [feuyeux/landscape#1]
interesting project, but can the command "landscape" be a little more shorter? I think a word with 10 letters is not easy to type frequently and correctly. 😆

**Comment by feuyeux** [comment]
you can achieve that through alias or mv landscape /usr/local/bin/{ur shorter}

**Comment by feuyeux** [comment]
further more, a cli tool should provide bash completion, to let users type tab to  auto-complete

**Comment by zhangsw1412** [comment]
get it! issue closed~ 👍
